# Generated by Django 4.1.13 on 2024-02-12 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_items"),
    ]

    operations = [
        migrations.AlterField(
            model_name="items",
            name="category_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.categories"
            ),
        ),
    ]
